### ISSUE TITLE
how i can find content :slug ?

### ISSUE THREAD

**Issue by BigO-Moha** [luisguve/strapi-plugin-ratings#1]
im trying to post reviews from the api directly but there is no usage docs! please show us an example ?

**Comment by luisguve** [comment]
Hi there, the `slug` part in `/api/ratings/reviews/:slug` for posting a review is a placeholder, you give it the value that works for your use case. It can be anything you want; e.g. if you have a blog, every post will be uniquely identified by a slug: `my-blog-post-title`, `other-blog-post`, etc., these strings will replace the `slug` part in the URL to post a review, as follows: `/api/ratings/reviews/my-blog-post-title`, `/api/ratings/reviews/other-blog-post`.

**Comment by BigO-Moha** [comment]
im using flutter for my front end what is the required json data variables ?

**Comment by luisguve** [comment]
The data that you are sending in the POST request seems right, but as I can see in the details field of the response, it looks like both the comment and score are undefined; they should be shown along with the slug, so I guess that's the problem, but I'm not sure how HTTP requests work in flutter.

**Comment by BigO-Moha** [comment]
im sending json data so which content type requires this plugin to accept data ? how i can pass data to the API. do you mean by Query Params or JSON

**Comment by luisguve** [comment]
The JSON looks right, just make sure that the ´Content-Type´ header is set to ´application/json´ in the HTTP request.

If it doesn't work, can you paste here the code in flutter that uploads the review?

**Comment by BigO-Moha** [comment]
thanks  fixed there was an issue with the  strapi v4.4.0-alpha.0 that i was using
