### ISSUE TITLE
How delete a rating?

### ISSUE THREAD

**Issue by tomaspasto24** [luisguve/strapi-plugin-ratings#2]
I don't know how delete a specific rating

**Comment by luisguve** [comment]
You can delete a specific review by going to the Ratings plugin page, then click on the review you want to delete, and then press the `Delete review` button

![ratings1](https://user-images.githubusercontent.com/33332372/196015564-59e9ab1a-d141-43f1-97ac-0249b60a3157.PNG)
![delete rating](https://user-images.githubusercontent.com/33332372/196015577-e11b3843-6fd5-49ba-96ea-f30c5b68b73f.P
![ratings2](https://user-images.githubusercontent.com/33332372/196015581-19606c82-a97f-45af-87a1-267394564d99.PNG)
NG)

**Comment by tomaspasto24** [comment]
Right, but I want delete specific review with API and I get this. 
![image](https://user-images.githubusercontent.com/60078552/196190413-ce29bf88-be8d-4111-a3fd-3ce2b858d909.png)
My English is basic, sorry. Thanks.

**Comment by luisguve** [comment]
Currently, there is no endpoint to delete or update reviews using the API.

Do you want to allow the author of the review to delete their review?

**Comment by tomaspasto24** [comment]
Yes, okey, thanks.
